### ISSUE TITLE
Segmentation fault, core dump when indexing reference fasta to mmi

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_tutorial_cdna_deseq2#3]
Hey,

Thanks for the tutorial. I managed to get it running with no problems on macOS with supplied RawData. When I try to repeat with my own data and installing on higher spec machine (Ubuntu 18), it runs error at the minimap2 index stage 

`rule minimap_ref_idx:
    input: ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
    output: ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi
    jobid: 1
    threads: 12

/bin/bash: line 1: 16745 Killed                  minimap2 -t 12 -k14 -w5 -d ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
[Mon Mar  4 02:33:32 2019]
Error in rule minimap_ref_idx:
    jobid: 1
    output: ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi

RuleException:
CalledProcessError in line 70 of /home/minion/cDNA_DESeq2/Snakefile:
Command ' set -euo pipefail;  minimap2 -t 12 -k14 -w5 -d ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz ' returned non-zero exit status 137.
  File "/home/minion/cDNA_DESeq2/Snakefile", line 70, in __rule_minimap_ref_idx
  File "/home/minion/miniconda3/envs/cDNA_DESeq2/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job minimap_ref_idx since they might be corrupted:
ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/minion/cDNA_DESeq2/.snakemake/log/2019-03-04T015334.679726.snakemake.log`

Within the same conda environment (i.e. within cDNA_DESeq folder) I ran minimap2 alone and it threw error:

` minimap2 -t 12 -k14 -w5 -d ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz.mmi ReferenceData/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz 
Segmentation fault (core dumped)`

I searched the issues of minimap2 on GitHub and there is similar issue but for much older version. 
The conda install provided the most up to date version 2.16 (r992). you think this is the issue:

https://github.com/lh3/minimap2/issues/47#issue-269293605 

However this was during mapping, not indexing, and it was fixed within newer version

I tried adding `=2.15` to the minimap2 part in the environment.yaml file but I am unsure how I can update the conda env to reinstall minimap2 to an older version.

**Comment by callumparr** [comment]
Ah I think I found similar issue within the ONT community. In this case indeed I think this is issue of my memory. I increase swapfile size to see if this solves problem. Previous it was only 1GB. So probably was full and caused the system dump.

**Comment by sagrudd** [comment]
Hi Callum - is this an issue that requires further assistance or did increased memory help? Thanks!

**Comment by callumparr** [comment]
I increased the memory swap and started it again last night and before I left it has mapped the first sample so I assume it ran ok. Although I won’t find out until tomorrow when I go into the lab I will close this issue.
