### ISSUE TITLE
Struggling with Rmarkdown

### ISSUE THREAD

**Issue by Jordthomas93** [nanoporetech/ont_tutorial_cdna_deseq2#4]
Hiya,

I completed the tutorial and have now ran snakemake using my own data by edititing the config file as you described.. however I am having an issue running the Rmarkdown for my own data? (Again I am very new to this so could be something stupid I have missed out)<

processing file: Nanopore_cDNA_Tutorial.Rmd
  |..                                                               |   2%
   inline R code fragments

  |...                                                              |   5%
label: unnamed-chunk-1 (with options)
List of 2
 $ echo   : logi FALSE
 $ include: logi FALSE

Quitting from lines 24-93 (Nanopore_cDNA_Tutorial.Rmd)
Error: The file does not exist: sE2_200219_reads.fastq.gz

(The sE2_200219_reads.fastq.gz is one of my files but it does exist!) Is there something else i need to change before running it?

Thanks for the help,

Jordan

**Comment by Jordthomas93** [comment]
Hiya
Thanks again for the quick response 

result of that commands is:

./Analysis/sE2_200219_reads.txt
./Analysis/flagstat/sE2_200219_reads.txt
./Analysis/Minimap/sE2_200219_reads.bam
./RawData/sE2_200219_reads.fastq.gz

and my config file:

---
# This is the configuration file for the Nanopore cDNA differential expression tutorial.
# The configuration must be specified in YAML format

# indentation is required as in this template - a single indent is 4 spaces


pipeline: "Nanopore cDNA gene expression profiling"

reference_genome: "ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

genome_annotation: "ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz"

Samples:
    - "sE2":   # this is a group 
        sE2: "sE2_200219_reads.fastq.gz"

    - "TZMbl":  # this is another group - names are arbitrary but must be unique
        TZMbl: "tzmbl_230119_reads.fastq.gz"
        
referenceGroup: "TZMbl"   # this name *must* match one of the group names       

readCountMinThreshold: 10   # what is the minimum number of transcripts for a gene feature to be considered
lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis

tutorialText: FALSE
# please change the tutorialText: value to FALSE to mask the tutorial instructions

(I am just trying it with two samples for now to get used to it)

Thanks again!

Jordan

**Comment by Jordthomas93** [comment]
Here is the config file if it makes it easier

**Comment by Jordthomas93** [comment]
---
# This is the configuration file for the Nanopore cDNA differential expression tutorial.
# The configuration must be specified in YAML format

# indentation is required as in this template - a single indent is 4 spaces


pipeline: "Nanopore cDNA gene expression profiling"

reference_genome: "ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

genome_annotation: "ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz"

Samples:
    - "sE2":   # this is a group 
        sE2: "sE2_200219_reads.fastq.gz"

    - "TZMbl":  # this is another group - names are arbitrary but must be unique
        TZMbl: "tzmbl_230119_reads.fastq.gz"
        
referenceGroup: "TZMbl"   # this name *must* match one of the group names       

readCountMinThreshold: 10   # what is the minimum number of transcripts for a gene feature to be considered
lfcThreshold : 1            # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis

tutorialText: FALSE
# please change the tutorialText: value to FALSE to mask the tutorial instructions

**Comment by sagrudd** [comment]
Dear Jordan,

If you have a look in the tutorial's config.yaml,

Samples:
    - "Condition 1":  
        A1: "RawData/condition1_rep1.fastq.gz"
        A2: "RawData/condition1_rep2.fastq.gz"

you can hopefully see that we provide the location of the fastq sequence files relative to the working directory (this is the RawData/ prefix). In your config.yaml file, you have provided the name of the sequence files, but without the RawData path prefix. The files are in the appropriate RawData directory. Please update your config.yaml and the R code should work.

I am a little surprised that Minimap2 and flagstat appear to have run; it would be worth re-running the analysis (rm -fR Analysis & snakemake -j 4) before trying the R code again?

Good luck - cheers - Stephen

**Comment by Jordthomas93** [comment]
Hiya

So that resolved the issue i was having but there is another hitch, i think possibly due to the amount of samples i have?

estimating size factors
estimating dispersions
Quitting from lines 323-345 (Nanopore_cDNA_Tutorial.Rmd)
Error in checkForExperimentalReplicates(object, modelMatrix) :

  The design matrix has the same number of samples and coefficients to fit,
  so estimation of dispersion is not possible. Treating samples
  as replicates was deprecated in v1.20 and no longer supported since v1.22.

Calls: <Anonymous> ... estimateDispersions -> .local -> checkForExperimentalReplicates
In addition: Warning messages:
1: In ncalc(width(fastq), n = 0.5) :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
2: In which(cumsum(len.sorted) >= sum(len.sorted) * n) :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
3: In ncalc(width(fastq), n = 0.9) :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'
4: In which(cumsum(len.sorted) >= sum(len.sorted) * n) :
  integer overflow in 'cumsum'; use 'cumsum(as.numeric(.))'


Thanks again for your help,

Jordan

**Comment by sagrudd** [comment]
Dear @Jordthomas93 - statistical tests do indeed prefer conditions with a sample size with n >> 1. The methods used for selecting genes that show differential expression are based on dispersion within the treatment groups and this is dependent on within group variance. This requires non-identical replicates. While scientifically not ideal, you could test the tutorial by subsampling your starting fastq files. The workflow requires at least two replicates for the control and experimental groups. seqtk has a good method for sampling reads and is available through conda.
