### ISSUE TITLE
Issue in Rmarkdown

### ISSUE THREAD

**Issue by Jordthomas93** [nanoporetech/ont_tutorial_cdna_deseq2#5]
Hiya Steven,

Thanks for the response. I realised I posted in the old thread, sorry about that! So the issue I am having is as follows: I have ran this tutorial with my samples successfully a few times now, its really useful and has helped alot! I have now tried to perform an analysis where i subset data sets and run this with the subsets and it is failing at the following stage on the Rmarkdown:

label: rsubread (with options)
List of 3
$ echo : logi FALSE
$ cache : logi FALSE
$ comment: logi NA

|........................... | 41%
ordinary text without R code

|............................. | 44%
label: geneCounts (with options)
List of 1
$ echo: logi FALSE

Quitting from lines 292-300 (Nanopore_cDNA_Tutorial.Rmd)
Error in .jcheck() :
Java Exception <no description because toString() failed>.jcall(cell, "V", "setCellValue", value)new("jobjRef", jobj = <pointer: 0x2f7f8928>, jclass = "java/lang/Throwable")
Calls: ... .write_block -> mapply -> -> .jcall -> .jcheck

The only difference is between the times it worked and didnt is that i have more replicates here. Previously I had been working with 3 where as this time i am working with +10. Considering that this is an issue in Java, is there a way to fix this issue? Thanks again for your continued support!

**Comment by sagrudd** [comment]
Dear Jord,

Thanks for the message. I am on the case and am looking into this. Please could you kindly send through your config.yaml and I will endeavour to replicate and fix this issue. Thanks for your patience!

**Comment by Jordthomas93** [comment]
Hiya

Thanks for the response!

Here is the config file.

Thanks and best wishes

JT

________________________________

**Comment by sagrudd** [comment]
Hei JT - in your response from last week, I don't see the config.yaml here - please could you re-attach?

Cheers

**Comment by sagrudd** [comment]
This issue is being closed; the error message indicates something java - likely to do with the Excel writing package (xlsx) - the tutorial has moved to a different R library (writexl) and I have been unable to replicate this error -
