### ISSUE TITLE
reference download and Rmarkdown script issues

### ISSUE THREAD

**Issue by Hanjiewu** [nanoporetech/ont_tutorial_cdna_deseq2#6]
1. While running the snakemake workflow, the error messages indicate connection failure:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/cDNA_DESeq2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/root/miniconda3/envs/cDNA_DESeq2/lib/python3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/root/miniconda3/envs/cDNA_DESeq2/lib/python3.7/site-packages/urllib3/connection.py", line 342, in connect
    self._tunnel()
  File "/root/miniconda3/envs/cDNA_DESeq2/lib/python3.7/http/client.py", line 921, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 503 Service Unavailable
```
By manually downloading the reference assembly and gtf annotation file to a ReferenceData folder and change the configure.yaml to "ReferenceData/reference.file.gz" can fix the issue.

2. Prepare the analysis report:
command:
`R --slave -e 'rmarkdown::render("Nanopore_cDNA_Tutorial.Rmd", "html_document")'`
the error message:
```
processing file: Nanopore_cDNA_Tutorial.Rmd

Error in dyn.load(file, DLLpath = DLLpath, ...) : 

  unable to load shared object '/root/miniconda3/envs/cDNA_DESeq2/lib/R/library/stringi/libs/stringi.so':

  libicui18n.so.64: cannot open shared object file: No such file or directory

Calls: <Anonymous> ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load

Execution halted
```
it seems the problem is the r-stringi installed from Conda-forge during in the tutorial installation.
https://github.com/conda-forge/r-stringi-feedstock/issues/20

Can someone figure it out and fix the issues?

Thanks

**Comment by Jordthomas93** [comment]
Hi

Did you have any solution to this? I am stuck on this too!

**Comment by Hanjiewu** [comment]
Reference genome and annotation download issue:
Manually download the reference assembly and gtf annotation file. In the config file, replace the url link with an explicit file path to the downloaded references. 

R-stringi issue:
re-install the "stringi" package
This can be achieved, in the tutorial conda environment, by typing the command

Rscript -e "install.packages('stringi', repos='http://cran.us.r-project.org')"

Good luck
